spring:
  application:
    name: App2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-service:3306/monitoringAPPDb?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

management:
  zipkin:
    tracing:
      endpoint: http://tempo.monitoring:9411/api/v2/spans
  endpoints:
    health:
      show:
        details: always
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    correlation: '[${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
