server:
  port: 8080


spring:
  profiles:
    active: dev
  application:
    name: App2
management:
  endpoints:
    web:
      exposure:
        include:  health, prometheus
  metrics:
    tags:
      application: ${spring.application.name}






