apiVersion: v1
kind: Service
metadata:
  name: app1-service
  labels:
    app: spring-svc
    job: app1-job
spec:
  type: NodePort
  selector:
    app: app1
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
