apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200

    distributor:
      receivers:
        zipkin:

    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/blocks


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo
          args: ["-config.file=/etc/tempo.yaml"]
          ports:
            - containerPort: 3200
            - containerPort: 9411
          volumeMounts:
            - name: tempo-config-volume
              mountPath: /etc/tempo.yaml
              subPath: tempo.yaml
            - name: tempo-data
              mountPath: /tmp/tempo
      volumes:
        - name: tempo-config-volume
          configMap:
            name: tempo-config
        - name: tempo-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: my-tempo
spec:
  type: NodePort
  ports:
    - name: tempo-http
      port: 3200
      targetPort: 3200
      nodePort: 30200
    - name: zipkin
      port: 9411
      targetPort: 9411
      nodePort: 30411
  selector:
    app: tempo
