apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: app2
          image: drissjabri/app2
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: MYSQL_HOST
              value: mysql-service
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USERNAME
              value: root
            - name: MYSQL_PASSWORD
              value: root

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app2-service-monitor
  labels:
    release: prometheus
spec:
  jobLabel: job
  endpoints:
    - interval: 5s
      path: /actuator/prometheus
      port: http
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: spring-svc
      job: app2-job