apiVersion: v1
kind: Service
metadata:
  name: app2-service
  labels:
    app: spring-svc
    job: app2-job
spec:
  type: NodePort
  selector:
    app: app2
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
