server:
  port : 8081
spring:
  application:
    name: App1
management:
  zipkin:
    tracing:
      endpoint: http://tempo.monitoring:9411/api/v2/spans
  endpoints:
    health:
      show:
        details: always
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    correlation: '[${spring.application.name:},%X{traceId:-},%X{spanId:-}]'


#elastic.apm:
#  service_name: app1
#  server_urls: http://fleet-service:8200
#  secret_token: MnlFOUVwRUI5bVlvRFRiUmRiMDA6UlpYQV9mWWZTNENEbEktUkwweS12UQ==
#  application_packages: org.example.app1