server:
  port : 8081
spring:
  application:
    name: App1
management:
  endpoints:
    web:
      exposure:
        include:  health, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

#elastic.apm:
#  service_name: app1
#  server_urls: http://fleet-service:8200
#  secret_token: MnlFOUVwRUI5bVlvRFRiUmRiMDA6UlpYQV9mWWZTNENEbEktUkwweS12UQ==
#  application_packages: org.example.app1