server:
  port : 8081
spring:
  application:
    name: App1
management:
  endpoints:
    web:
      exposure:
        include:  health, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

