name: CI for App1

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Build the application
        run: |
          cd "Spring boot applications/App1"
          mvn clean
          mvn -B package --file pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: "Spring boot applications/App1"
          file: "Spring boot applications/App1/Dockerfile"
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/app1:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: "Spring boot applications/App1"
          file: "Spring boot applications/App1/Dockerfile"
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/app1:latest
